VocabuleryX/Controllers/DictionaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;
using VocabuleryX.DAL.Entities;
using VocabuleryX.DAL.Repositories;

namespace VocabuleryX.Controllers
{
    public class DictionaryController : Controller
    {
        private readonly EFUnitOfWork db;

        public DictionaryController()
        {
            db = new EFUnitOfWork();
        }

        public ActionResult Index()
        {
            var words = db.Words.GetAll().OrderByDescending(x=>x.Id);
            return View(words);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Translation")] Word word)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var oldWord = db.Words.Get(word.Id);
            if (oldWord == null)
            {
                return new HttpNotFoundResult();
            }

            oldWord.Name = word.Name;
            oldWord.Translation = word.Translation;
            db.Words.Update(oldWord);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Status, ProcessDate")] Word word)
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Words.Create(word);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (db.Words.Delete(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotModified);
            }
        }

        //public ActionResult CreateWord(string origin, string version)
        //{
        //    //Thread.Sleep(2000);
        //    var existOne = unitOfWork.Words.Find(x => x.Origin == origin).FirstOrDefault();
        //    if ( existOne != null)
        //    {
        //        Response.StatusCode = 400;
        //        return Content("duplicate");
        //    }
        //    var word = new Word() {Origin = origin, Version = version};
        //    unitOfWork.Words.Create(word);
        //    return Json(word);
        //}

        //public ActionResult DeleteWord(int id)
        //{
        //    if (unitOfWork.Words.Delete(id))
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.OK);
        //    }
        //    return new HttpStatusCodeResult(HttpStatusCode.NotFound);
        //}

        //public ActionResult UpdateWord(Word word)
        //{
        //    var item = unitOfWork.Words.Find(x=>x.Id == word.Id).First();
        //    if (item != null)
        //    {
        //        item.Origin = word.Origin;
        //        item.Version = word.Version;
        //        unitOfWork.Words.Update(item);
        //        return new HttpStatusCodeResult(HttpStatusCode.OK);
        //    }
        //    return new HttpStatusCodeResult(HttpStatusCode.NotFound);
        //}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

VocabuleryX/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VocabuleryX.DAL.Entities;
using VocabuleryX.DAL.Repositories;
using VocabuleryX.Models;

namespace VocabuleryX.Controllers
{
    public class ImportController : Controller
    {
        private EFUnitOfWork db;

        public ImportController()
        {
            db = new EFUnitOfWork();
        }

        // GET: Import
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(WordImportViewModel[] words)
        {
            List<WordImportFailViewModel> failWords = new List<WordImportFailViewModel>();
            foreach (var word in words)
            {
                string error;
                if (Validate(word, out error))
                {
                    db.Words.Create(new Word() {Name = word.Name, Translation = word.Translation});
                }
                else
                {
                    failWords.Add(new WordImportFailViewModel() { Name = word.Name, Translation = word.Translation, Error = error });
                }
            }
            return Json(failWords);
        }

        private bool Validate(WordImportViewModel word, out string error)
        {
            if (string.IsNullOrEmpty(word.Name))
            {
                error = "Text is empty";
                return false;
            }

            if (string.IsNullOrEmpty(word.Translation))
            {
                error = "Translation is empty";
                return false;
            }

            var existWord = db.Words.Find(x => x.Name == word.Name).FirstOrDefault();
            if (existWord != null)
            {
                error = "Duplicate word";
                return false;
            }

            error = string.Empty;
            return true;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

VocabuleryX/Views/Dictionary/Index.cshtml
@model IEnumerable<VocabuleryX.DAL.Entities.Word>
@{
    ViewBag.Title = "Dictionary";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@section scripts{
    @Styles.Render("~/Scripts/js-grid/jsgrid.min.css")
    @Styles.Render("~/Scripts/js-grid/jsgrid-theme.min.css")
    @*@Scripts.Render("~/Scripts/js-grid/jsgrid.min.js")*@
    @Styles.Render("~/Scripts/admin/dictionary.css")
    @Scripts.Render("~/Scripts/admin/dictionary.js");
    @*@Styles.Render("~/Content/dictionary.css")
    @Scripts.Render("~/Scripts/Div/dictionary.js");*@
}

<div class="import">
    <a class="btn btn-default" href="@Url.Action("Index", "Import")">Import</a>     
</div>
<div id="jsGrid">

</div>

<script src="~/Scripts/js-grid/jsgrid.min.js" type="text/javascript"></script>
<script type="text/javascript">
    
    var dataSource = @Html.Raw(Json.Encode(Model));

    $('#jsGrid').jsGrid({
        width: "800px",
        height: "450px",

        align: "center",

        inserting: true,
        editing: true,
        sorting: true,
        paging: true,

        pageButtonCount: 5,
        pageSize: 10,

        data: dataSource,

        fields: [
            { name: "Name", type: "text", width: 300, validate: "required" },
            { name: "Translation", type: "text", width: 300, validate: "required" },
            { name: "Status", type: "number", width: 100 },
            { type: "control" }
        ],

        controller: {
            insertItem: function(item) {
                $.ajax({
                    url: '@Url.Action("Create", "Dictionary", null, "http", "localhost")',
                    type: "POST",
                    data: item,
                    success: function(data, status) {
                        //alert(status);
                    },
                    error:function(request, status, error) {
                        //alert(status);
                    }
                });
            },
            updateItem: function(item) {
                $.ajax({
                    url: '@Url.Action("Edit", "Dictionary", null, "http", "localhost")',
                    type: "POST",
                    data: item,
                    success: function(data, status) {
                        //alert(status);
                    },
                    error:function(request, status, error) {
                        //alert(status);
                    }
                });
            },
            deleteItem: function(item) {
                $.ajax({
                    url: '@Url.Action("Delete", "Dictionary", null, "http", "localhost")',
                    type: "POST",
                    data: item,
                    success: function(data, status) {
                        //alert(status);
                    },
                    error:function(request, status, error) {
                        //alert(status);
                    }
                });
            }
        }
    });


    //$('#jsGrid').jsGrid("loadData", data).done(function() {
    //    alert('huy');
    //});
</script>




<!--@*<div class="row-functions">
    <div class="container">
        <div>
            <a data-toggle="collapse" href="#createWordPanel" class="btn btn-default"><span>Create a new word.</span></a>
        </div>
        <div id="createWordPanel" class="collapse">
            @using (Ajax.BeginForm("CreateWord", "Dictionary", null, new AjaxOptions() {OnBegin = "OnBegin", OnSuccess = "OnSuccess", OnFailure = "OnFailure", OnComplete = "OnComplete", LoadingElementId = "loadingBar", LoadingElementDuration = 100}, new {@class = "form-horizontal", id = "createWordForm"}))
            {
                <hr/>
                <div class="form-group">
                    @Html.Label("txtOrigin", "Origin", new {@class = "control-label col-md-1"})
                    <div class="col-md-5">
                        @Html.TextBox("origin", "", new {@class = "form-control", id = "txtOrigin"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.Label("txtVersion", "Version", new {@class = "control-label col-md-1"})
                    <div class="col-md-5">
                        @Html.TextBox("version", "", new {@class = "form-control", id = "txtVersion"})
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-1 col-md-1">
                        <button class="btn btn-default" id="btnNewWord">Add</button>
                    </div>
                    <div class="col-md-4">
                        <div id="loadingBar">
                            <span class="fa fa-spinner fa-spin"></span><span> Loading...</span>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div>
    <div>
        
    </div>
</div>


<div class="grid-wrapper">
    <div class="grid">
        <table class="table table-hover" id="dataGrid">
            <thead>
            <tr>
                <th class="grid-col-1">
                    <div class="grid-col-1"></div></th>
                <th class="grid-col-2">
                    <div class="grid-col-2">Word</div></th>
                <th class="grid-col-3">
                    <div class="grid-col-3">Translation</div></th>
                <th class="grid-col-4">
                    <div class="grid-col-4 text-center">Status</div></th>
                <th class="grid-col-5">
                    <div class="grid-col-5 text-center">Action</div></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr data-id="@item.Id">
                    <td>
                        <button class="btn btn-default">
                            <span class="glyphicon glyphicon-play-circle" aria-hidden="true" name="speech"></span>
                        </button>
                    </td>
                    <td>
                        <span class="word-origin row-read">@item.Origin</span>
                        <input class="input-sm word-origin row-edit" value="sample">
                    </td>
                    <td>
                        <span class="word-version row-read">@item.Version</span>
                        <input class="input-sm word-version row-edit" value="primer">
                    </td>
                    <td class="text-center">
                        <span class="glyphicon glyphicon-ok-circle" name="status"></span>
                    </td>
                    <td class="text-center">
                        <button class="btn btn-default row-read" name="btnEdit">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </button>
                        <button class="btn btn-default row-read" name="btnRemove">
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </button>
                        <button class="btn btn-default row-edit" name="btnEditOk">
                            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                        </button>
                        <button class="btn btn-default row-edit" name="btnEditCancel">
                            <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
                        </button>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>*@

-->